version: "3"

services:
  app:
    build:
      context: .
      args:
        VARIANT: "2.6"
        BUNDLER_VERSION: "1.3.0"
        RAILS_VERSIONS: "5.1.2"
        NODE_VERSION: "14"
    environment:
      BINDING: 0.0.0.0
    volumes:
      - ..:/home/vscode/environment:cached
      - bundle-volume:/usr/local/bundle
    command: sleep infinity
volumes:
  bundle-volume:
